### ISSUE TITLE
Feature request: Use default browser when opening URL

### ISSUE THREAD

**Issue by osapon** [rhysd/Mstdn#14]
I'd like to open URL with a default browser.
But it is considered difficult to distinguish the instance URL and another site URL, I think good way to copy the URL from the context menu.

**Comment by rhysd** [comment]
Yes, that *was* default behavior. App prevented creating frameless window at `new-window` event and opened the page in external browser instead.

However, Electron now has a crash bug on preventing the event. As workaround, now app does not prevent the event. I would back the default behavior to previous when the bug is fixed.

https://github.com/electron/electron/issues/9230

**Comment by rhysd** [comment]
Downgrading Electron version may solve this issue. However, downgrading Electron version also means downgrading Chromium version. Chromium's data resources management (things in `Mstdn` directory) does not consider the case in which downgrading Chromium version. So downgrading Electron version may break user data and should be avoided.

**Comment by rhysd** [comment]
Electron 1.6.8 beta fixed the bug. I'll upgrade dependent Electron version in next release.
